const db = require('../config/db');
const pdfFormService = require('./pdfFormService');

class AutoFillService {
  constructor() {
    this.formFieldMappings = {
      // Common fields that can be auto-fetched
      name: 'faculty_data',
      designation: 'faculty_data',
      department: 'faculty_data',
      employeeId: 'faculty_data',
      
      // Fields that need user input
      leaveDaysWithDate: 'user_input',
      reason: 'user_input',
      noOfDaysLeave: 'calculated',
      leaveFromDate: 'user_input',
      leaveToDate: 'user_input',
      contactNo: 'user_input',
      addressLine1: 'user_input',
      addressLine2: 'user_input',
      addressLine3: 'user_input',
      
      // Auto-generated fields
      applicationDate: 'auto_generated',
      
      // Admin fields
      applicationStatus: 'admin_only',
      grantedNotGranted: 'admin_only'
    };
  }

  // Get faculty data from database
  async getFacultyData(facultyId) {
    try {
      const query = `
        SELECT 
          id,
          firstName,
          lastName,
          email,
          designation,
          department,
          employeeId,
          phone,
          address,
          faculty_type
        FROM users 
        WHERE id = ? AND role = 'faculty'
      `;
      
      const [rows] = await db.execute(query, [facultyId]);
      
      if (rows.length === 0) {
        throw new Error('Faculty not found');
      }
      
      return rows[0];
    } catch (error) {
      console.error('Error fetching faculty data:', error);
      throw error;
    }
  }

  // Get form structure with auto-filled and required fields
  async getFormStructureWithData(formType, staffType, facultyId) {
    try {
      const facultyData = await this.getFacultyData(facultyId);
      const formPositions = require('../config/formPositions.json');
      
      const positions = formPositions[staffType]?.[formType] || {};
      const formFields = [];
      
      // Process each field in the form
      for (const [fieldName, position] of Object.entries(positions)) {
        const fieldInfo = {
          name: fieldName,
          position: position,
          type: this.getFieldType(fieldName),
          required: this.isFieldRequired(fieldName),
          source: this.formFieldMappings[fieldName] || 'user_input',
          value: null,
          options: null
        };
        
        // Auto-fill available data
        switch (fieldInfo.source) {
          case 'faculty_data':
            fieldInfo.value = this.getFacultyFieldValue(fieldName, facultyData);
            fieldInfo.readonly = true;
            break;
            
          case 'auto_generated':
            fieldInfo.value = this.getAutoGeneratedValue(fieldName);
            fieldInfo.readonly = true;
            break;
            
          case 'calculated':
            fieldInfo.readonly = true;
            fieldInfo.dependsOn = this.getCalculationDependencies(fieldName);
            break;
            
          case 'admin_only':
            fieldInfo.readonly = true;
            fieldInfo.adminOnly = true;
            break;
            
          default:
            // user_input fields
            if (fieldName.includes('natureOfLeave')) {
              fieldInfo.type = 'checkbox';
              fieldInfo.options = this.getLeaveTypeOptions();
            }
        }
        
        formFields.push(fieldInfo);
      }
      
      return {
        formType,
        staffType,
        facultyData,
        formFields,
        metadata: {
          totalFields: formFields.length,
          autoFilledFields: formFields.filter(f => f.value !== null).length,
          requiredFields: formFields.filter(f => f.required && !f.readonly).length
        }
      };
      
    } catch (error) {
      console.error('Error getting form structure with data:', error);
      throw error;
    }
  }

  // Get field type based on field name
  getFieldType(fieldName) {
    if (fieldName.includes('Date')) return 'date';
    if (fieldName.includes('natureOfLeave') || fieldName.includes('reason') && fieldName !== 'reason') return 'checkbox';
    if (fieldName.includes('address') || fieldName === 'reason') return 'textarea';
    if (fieldName.includes('contactNo') || fieldName.includes('phone')) return 'tel';
    if (fieldName.includes('email')) return 'email';
    if (fieldName.includes('noOfDays')) return 'number';
    return 'text';
  }

  // Check if field is required
  isFieldRequired(fieldName) {
    const requiredFields = [
      'name', 'designation', 'leaveDaysWithDate', 'reason', 
      'leaveFromDate', 'leaveToDate', 'noOfDaysLeave'
    ];
    return requiredFields.includes(fieldName);
  }

  // Get faculty field value
  getFacultyFieldValue(fieldName, facultyData) {
    const mapping = {
      name: `${facultyData.firstName} ${facultyData.lastName}`,
      designation: facultyData.designation,
      department: facultyData.department,
      employeeId: facultyData.employeeId,
      contactNo: facultyData.phone,
      addressLine1: facultyData.address
    };
    
    return mapping[fieldName] || '';
  }

  // Get auto-generated values
  getAutoGeneratedValue(fieldName) {
    switch (fieldName) {
      case 'applicationDate':
        return new Date().toLocaleDateString('en-GB');
      default:
        return '';
    }
  }

  // Get calculation dependencies
  getCalculationDependencies(fieldName) {
    switch (fieldName) {
      case 'noOfDaysLeave':
        return ['leaveFromDate', 'leaveToDate'];
      default:
        return [];
    }
  }

  // Get leave type options
  getLeaveTypeOptions() {
    return [
      { value: 'EL', label: 'Earned Leave' },
      { value: 'HPL', label: 'Half Pay Leave' },
      { value: 'COML', label: 'Commuted Leave' },
      { value: 'EOL', label: 'Extra Ordinary Leave' }
    ];
  }

  // Calculate leave days
  calculateLeaveDays(startDate, endDate) {
    if (!startDate || !endDate) return 0;
    
    const start = new Date(startDate);
    const end = new Date(endDate);
    const timeDiff = end.getTime() - start.getTime();
    return Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1;
  }

  // Validate form data
  validateFormData(formData, formFields) {
    const errors = [];
    
    formFields.forEach(field => {
      if (field.required && !field.readonly && !formData[field.name]) {
        errors.push(`${field.name} is required`);
      }
      
      // Type-specific validations
      if (formData[field.name]) {
        switch (field.type) {
          case 'date':
            if (!this.isValidDate(formData[field.name])) {
              errors.push(`${field.name} must be a valid date`);
            }
            break;
            
          case 'tel':
            if (!this.isValidPhone(formData[field.name])) {
              errors.push(`${field.name} must be a valid phone number`);
            }
            break;
            
          case 'email':
            if (!this.isValidEmail(formData[field.name])) {
              errors.push(`${field.name} must be a valid email`);
            }
            break;
        }
      }
    });
    
    // Cross-field validations
    if (formData.leaveFromDate && formData.leaveToDate) {
      const startDate = new Date(formData.leaveFromDate);
      const endDate = new Date(formData.leaveToDate);
      
      if (startDate > endDate) {
        errors.push('Leave start date cannot be after end date');
      }
    }
    
    return errors;
  }

  // Validation helpers
  isValidDate(dateString) {
    const date = new Date(dateString);
    return date instanceof Date && !isNaN(date);
  }

  isValidPhone(phone) {
    const phoneRegex = /^[\+]?[1-9][\d]{0,15}$/;
    return phoneRegex.test(phone.replace(/\s/g, ''));
  }

  isValidEmail(email) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  // Process form submission
  async processFormSubmission(formData, formType, staffType, facultyId) {
    try {
      const formStructure = await this.getFormStructureWithData(formType, staffType, facultyId);
      
      // Validate form data
      const validationErrors = this.validateFormData(formData, formStructure.formFields);
      if (validationErrors.length > 0) {
        throw new Error(`Validation failed: ${validationErrors.join(', ')}`);
      }
      
      // Calculate derived fields
      if (formData.leaveFromDate && formData.leaveToDate) {
        formData.noOfDaysLeave = this.calculateLeaveDays(formData.leaveFromDate, formData.leaveToDate);
      }
      
      // Merge with auto-filled data
      const completeFormData = this.mergeFormData(formData, formStructure);
      
      // Generate PDF
      const pdfResult = await pdfFormService.generateLeaveForm(
        formStructure.facultyData,
        completeFormData,
        staffType
      );
      
      // Save to database
      const leaveApplicationId = await this.saveLeaveApplication(
        facultyId,
        completeFormData,
        formType,
        staffType
      );
      
      return {
        success: true,
        leaveApplicationId,
        pdfResult,
        formData: completeFormData
      };
      
    } catch (error) {
      console.error('Error processing form submission:', error);
      throw error;
    }
  }

  // Merge user input with auto-filled data
  mergeFormData(userInput, formStructure) {
    const mergedData = { ...userInput };
    
    formStructure.formFields.forEach(field => {
      if (field.value !== null && !userInput[field.name]) {
        mergedData[field.name] = field.value;
      }
    });
    
    return mergedData;
  }

  // Save leave application to database
  async saveLeaveApplication(facultyId, formData, formType, staffType) {
    try {
      const query = `
        INSERT INTO leave_applications (
          faculty_id,
          leave_type,
          start_date,
          end_date,
          no_of_days,
          reason,
          contact_during_leave,
          address_during_leave,
          form_type,
          staff_type,
          application_date,
          status,
          form_data
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?)
      `;
      
      const addressDuringLeave = [
        formData.addressLine1,
        formData.addressLine2,
        formData.addressLine3
      ].filter(Boolean).join(', ');
      
      const values = [
        facultyId,
        this.getLeaveTypeFromForm(formData),
        formData.leaveFromDate || formData.startDate,
        formData.leaveToDate || formData.endDate,
        formData.noOfDaysLeave,
        formData.reason,
        formData.contactNo,
        addressDuringLeave,
        formType,
        staffType,
        new Date(),
        JSON.stringify(formData)
      ];
      
      const [result] = await db.execute(query, values);
      return result.insertId;
      
    } catch (error) {
      console.error('Error saving leave application:', error);
      throw error;
    }
  }

  // Extract leave type from form data
  getLeaveTypeFromForm(formData) {
    if (formData.natureOfLeave_EL) return 'Earned Leave';
    if (formData.natureOfLeave_HPL) return 'Half Pay Leave';
    if (formData.natureOfLeave_COML) return 'Commuted Leave';
    if (formData.natureOfLeave_EOL) return 'Extra Ordinary Leave';
    return 'Casual Leave';
  }

  // Get available forms for faculty
  async getAvailableFormsForFaculty(facultyId) {
    try {
      const facultyData = await this.getFacultyData(facultyId);
      const staffType = this.determineStaffType(facultyData);
      const contractType = this.determineContractType(facultyData);
      
      const availableForms = [];
      const formTypes = ['CL_Form', 'EL_Form', 'Leave_Form'];
      
      for (const formType of formTypes) {
        const formStructure = await this.getFormStructureWithData(formType, staffType, facultyId);
        availableForms.push({
          formType,
          displayName: this.getFormDisplayName(formType),
          description: this.getFormDescription(formType),
          staffType,
          contractType,
          fieldCount: formStructure.formFields.length,
          autoFilledFields: formStructure.metadata.autoFilledFields,
          requiredFields: formStructure.metadata.requiredFields
        });
      }
      
      return {
        facultyData,
        staffType,
        contractType,
        availableForms
      };
      
    } catch (error) {
      console.error('Error getting available forms:', error);
      throw error;
    }
  }

  // Determine staff type from faculty data
  determineStaffType(facultyData) {
    const teachingDesignations = ['professor', 'assistant professor', 'associate professor', 'lecturer'];
    const designation = (facultyData.designation || '').toLowerCase();
    
    if (teachingDesignations.some(d => designation.includes(d))) {
      return 'Teaching';
    }
    return 'Non-Teaching';
  }

  // Determine contract type
  determineContractType(facultyData) {
    if (facultyData.faculty_type === 'contract' || 
        (facultyData.designation && facultyData.designation.toLowerCase().includes('contract'))) {
      return 'Contract';
    }
    return 'Regular';
  }

  // Get form display names
  getFormDisplayName(formType) {
    const names = {
      'CL_Form': 'Casual Leave Form',
      'EL_Form': 'Earned Leave Form',
      'Leave_Form': 'General Leave Form'
    };
    return names[formType] || formType;
  }

  // Get form descriptions
  getFormDescription(formType) {
    const descriptions = {
      'CL_Form': 'For casual leave, compensatory leave, RH leave, and special leave applications',
      'EL_Form': 'For earned leave, half pay leave, commuted leave, and extraordinary leave applications',
      'Leave_Form': 'For general leave applications including maternity, paternity, and study leave'
    };
    return descriptions[formType] || '';
  }
}

module.exports = new AutoFillService();